version: '3.8'

services:
  starlink-tvbox:
    # 因为您使用 1Panel，它可以直接在服务器上帮您一键编译打包，无需借助外部镜像仓库！
    build: .
    container_name: starlink-tvbox-api
    ports:
      - "8089:8089"
    # 如果您直接修改本文件，请确保以下参数符合您的实际情况：
    environment:
      - REG_CODE=888888          # 用户注册时的邀请码
      - SECRET_KEY=change_me_now  # Flask Session 密钥，请务必修改
      - BASE_URL=                 # 外部访问基础 URL，一般留空即可自动识别
    volumes:
      - ./data:/app/data         # 冒号左边 ./data 是您服务器上的持久化目录
    restart: unless-stopped
